spring.application.name=coursedemo
server.port=8060

management.server.port=8061
management.endpoints.web.base-path=/manage


# 2. Silence the feature probe logs
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate.orm.jdbc.dialect=ERROR
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreationHelper=OFF

# 3. Ensure Derby creates the DB silently
spring.datasource.url=jdbc:derby:memory:coursedemo;create=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


